"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
const urlShorten_controller_1 = require("../../controllers/urlShorten.controller");
router.get("/get", urlShorten_controller_1.getShortURL);
router.delete("/delete", urlShorten_controller_1.deleteShortURL);
router.get("/redirect", urlShorten_controller_1.redirectToURL);
router.post("/create", urlShorten_controller_1.createShortURL);
exports.default = router;
